// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: logs/v1/record.proto

package logsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Checksum      uint32                 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ProducerId    string                 `protobuf:"bytes,4,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_logs_v1_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_logs_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Record) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *Record) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *Record) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_logs_v1_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_logs_v1_record_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_logs_v1_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_logs_v1_record_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_logs_v1_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_logs_v1_record_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_logs_v1_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_v1_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_logs_v1_record_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_logs_v1_record_proto protoreflect.FileDescriptor

const file_logs_v1_record_proto_rawDesc = "" +
	"\n" +
	"\x14logs/v1/record.proto\x12\x06logsv1\"\x92\x01\n" +
	"\x06Record\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksum\x12\x1f\n" +
	"\vproducer_id\x18\x04 \x01(\tR\n" +
	"producerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"8\n" +
	"\x0eProduceRequest\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.logsv1.RecordR\x06record\")\n" +
	"\x0fProduceResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\"(\n" +
	"\x0eConsumeRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\"9\n" +
	"\x0fConsumeResponse\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.logsv1.RecordR\x06recordBs\n" +
	"\n" +
	"com.logsv1B\vRecordProtoP\x01Z github.com/ccrabbai/logos/logsv1\xa2\x02\x03LXX\xaa\x02\x06Logsv1\xca\x02\x06Logsv1\xe2\x02\x12Logsv1\\GPBMetadata\xea\x02\x06Logsv1b\x06proto3"

var (
	file_logs_v1_record_proto_rawDescOnce sync.Once
	file_logs_v1_record_proto_rawDescData []byte
)

func file_logs_v1_record_proto_rawDescGZIP() []byte {
	file_logs_v1_record_proto_rawDescOnce.Do(func() {
		file_logs_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_v1_record_proto_rawDesc), len(file_logs_v1_record_proto_rawDesc)))
	})
	return file_logs_v1_record_proto_rawDescData
}

var file_logs_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_logs_v1_record_proto_goTypes = []any{
	(*Record)(nil),          // 0: logsv1.Record
	(*ProduceRequest)(nil),  // 1: logsv1.ProduceRequest
	(*ProduceResponse)(nil), // 2: logsv1.ProduceResponse
	(*ConsumeRequest)(nil),  // 3: logsv1.ConsumeRequest
	(*ConsumeResponse)(nil), // 4: logsv1.ConsumeResponse
}
var file_logs_v1_record_proto_depIdxs = []int32{
	0, // 0: logsv1.ProduceRequest.record:type_name -> logsv1.Record
	0, // 1: logsv1.ConsumeResponse.record:type_name -> logsv1.Record
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logs_v1_record_proto_init() }
func file_logs_v1_record_proto_init() {
	if File_logs_v1_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_v1_record_proto_rawDesc), len(file_logs_v1_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logs_v1_record_proto_goTypes,
		DependencyIndexes: file_logs_v1_record_proto_depIdxs,
		MessageInfos:      file_logs_v1_record_proto_msgTypes,
	}.Build()
	File_logs_v1_record_proto = out.File
	file_logs_v1_record_proto_goTypes = nil
	file_logs_v1_record_proto_depIdxs = nil
}
