// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: logs/v1/service.proto

package logsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_logs_v1_service_proto protoreflect.FileDescriptor

const file_logs_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15logs/v1/service.proto\x12\x06logsv1\x1a\x14logs/v1/record.proto2\x87\x02\n" +
	"\x03Log\x12:\n" +
	"\aProduce\x12\x16.logsv1.ProduceRequest\x1a\x17.logsv1.ProduceResponse\x12:\n" +
	"\aConsume\x12\x16.logsv1.ConsumeRequest\x1a\x17.logsv1.ConsumeResponse\x12B\n" +
	"\rConsumeStream\x12\x16.logsv1.ConsumeRequest\x1a\x17.logsv1.ConsumeResponse0\x01\x12D\n" +
	"\rProduceStream\x12\x16.logsv1.ProduceRequest\x1a\x17.logsv1.ProduceResponse(\x010\x01Bt\n" +
	"\n" +
	"com.logsv1B\fServiceProtoP\x01Z github.com/ccrabbai/logos/logsv1\xa2\x02\x03LXX\xaa\x02\x06Logsv1\xca\x02\x06Logsv1\xe2\x02\x12Logsv1\\GPBMetadata\xea\x02\x06Logsv1b\x06proto3"

var file_logs_v1_service_proto_goTypes = []any{
	(*ProduceRequest)(nil),  // 0: logsv1.ProduceRequest
	(*ConsumeRequest)(nil),  // 1: logsv1.ConsumeRequest
	(*ProduceResponse)(nil), // 2: logsv1.ProduceResponse
	(*ConsumeResponse)(nil), // 3: logsv1.ConsumeResponse
}
var file_logs_v1_service_proto_depIdxs = []int32{
	0, // 0: logsv1.Log.Produce:input_type -> logsv1.ProduceRequest
	1, // 1: logsv1.Log.Consume:input_type -> logsv1.ConsumeRequest
	1, // 2: logsv1.Log.ConsumeStream:input_type -> logsv1.ConsumeRequest
	0, // 3: logsv1.Log.ProduceStream:input_type -> logsv1.ProduceRequest
	2, // 4: logsv1.Log.Produce:output_type -> logsv1.ProduceResponse
	3, // 5: logsv1.Log.Consume:output_type -> logsv1.ConsumeResponse
	3, // 6: logsv1.Log.ConsumeStream:output_type -> logsv1.ConsumeResponse
	2, // 7: logsv1.Log.ProduceStream:output_type -> logsv1.ProduceResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logs_v1_service_proto_init() }
func file_logs_v1_service_proto_init() {
	if File_logs_v1_service_proto != nil {
		return
	}
	file_logs_v1_record_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_v1_service_proto_rawDesc), len(file_logs_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_v1_service_proto_goTypes,
		DependencyIndexes: file_logs_v1_service_proto_depIdxs,
	}.Build()
	File_logs_v1_service_proto = out.File
	file_logs_v1_service_proto_goTypes = nil
	file_logs_v1_service_proto_depIdxs = nil
}
